#!/usr/bin/env node
// Builds dist/ for the GitHub Action: copies src/ verbatim into dist/lib/ and
// writes a two-line entry point. No bundler and no dependencies; CI checks
// that the committed dist/ matches a fresh build.

import { cpSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(root, 'dist');

rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });
cpSync(join(root, 'src'), join(dist, 'lib'), {
  recursive: true,
  filter: (src) => !src.endsWith('cli.js'),
});
writeFileSync(join(dist, 'package.json'), `${JSON.stringify({ type: 'module', private: true }, null, 2)}\n`);
writeFileSync(
  join(dist, 'index.js'),
  [
    '// Generated by scripts/build-dist.js. Do not edit; edit src/ and run `npm run build`.',
    "import { runAction } from './lib/action.js';",
    '',
    'process.exitCode = await runAction();',
    '',
  ].join('\n'),
);
console.log('dist/ rebuilt from src/');
